# Generated by Django 4.0.3 on 2022-03-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_inventory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
